apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: "mysql-namespace"
  labels:
    app: mysql-label
    app.kubernetes.io/name: mysql-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql-label
  template:
    metadata:
      labels:
        app: mysql-label
    spec:
      containers:
      - name: mysql-app
        image: williansmartins/app-mysql:v1
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "mypassword"
        ports:
          - containerPort: 3306
  strategy:
    type: RollingUpdate

